# Generated by Django 2.0.1 on 2018-01-30 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20180124_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='difficulty',
            options={'verbose_name_plural': 'difficulties'},
        ),
    ]
