# Generated by Django 2.0.1 on 2018-01-30 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20180130_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='attachment_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Image'), (2, 'Text'), (3, 'Code')], default=1),
            preserve_default=False,
        ),
    ]
