# Generated by Django 2.0.1 on 2018-01-30 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_attachment_attachment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='attachment_type',
            new_name='type',
        ),
    ]
