# Generated by Django 2.0.1 on 2018-01-30 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20180130_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='type',
            new_name='kind',
        ),
    ]
