# Generated by Django 2.0.1 on 2018-01-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20180130_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='kind',
            field=models.CharField(choices=[('IMG', 'Image'), ('TEXT', 'Text'), ('CODE', 'Code')], max_length=10),
        ),
    ]
